version: "3"
services:
  akitu-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_AUTH_TOKEN=${NEXT_PUBLIC_AUTH_TOKEN}
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
        - NEXT_PUBLIC_COUNTRIES_STATE_CITY_API_KEY=${NEXT_PUBLIC_COUNTRIES_STATE_CITY_API_KEY}
    image: akitu-dashboard
    container_name: akitu-dashboard
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_AUTH_TOKEN=${NEXT_PUBLIC_AUTH_TOKEN}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - NEXT_PUBLIC_COUNTRIES_STATE_CITY_API_KEY=${NEXT_PUBLIC_COUNTRIES_STATE_CITY_API_KEY}
    restart: unless-stopped

